CREATE TABLE "TRADIA"."MESSAGE_TYPES"("MESSAGE_TYPE_ID" VARCHAR2(
    2) NOT NULL, "TYPE_NAME" VARCHAR2(2) NOT NULL, 
    "TYPE_DESCRIPTION" VARCHAR2(30) NOT NULL, 
    CONSTRAINT "PK_MSGTYPE" PRIMARY KEY("MESSAGE_TYPE_ID"), 
    CONSTRAINT "UQ_MSGTYPE" UNIQUE("MESSAGE_TYPE_ID")) 
    TABLESPACE "TRADIA" 