CREATE TABLE "TRADIA"."ACCOUNT_TYPES"("ACCOUNT_TYPE_ID" VARCHAR2(
    2) NOT NULL, "ACCOUNT_DESCRIPTION" VARCHAR2(30) NOT NULL, 
    CONSTRAINT "PK_ACC_TYPE" PRIMARY KEY("ACCOUNT_TYPE_ID"), 
    CONSTRAINT "UQ_ACC_TYPE" UNIQUE("ACCOUNT_TYPE_ID")) 
    TABLESPACE "TRADIA"