CREATE TABLE "TRADIA"."ISINCODES"("ISIN_CODE_ID" VARCHAR2(20) 
    NOT NULL, "STOCK_NAME" VARCHAR2(50) NOT NULL, 
    CONSTRAINT "PK_ISIN" PRIMARY KEY("ISIN_CODE_ID"), 
    CONSTRAINT "UQ_ISIN" UNIQUE("ISIN_CODE_ID")) 
    TABLESPACE "TRADIA" 