CREATE TABLE "TRADIA"."CUSTOMERS"("CUSTOMER_ID" VARCHAR2(10) NOT 
    NULL, "TITLE" VARCHAR2(4) NOT NULL, "NAME" VARCHAR2(20) NOT NULL, 
    "MIDDLE" VARCHAR2(1) NOT NULL, "SURNAME" VARCHAR2(50) NOT NULL, 
    "ADDRESS" VARCHAR2(50) NOT NULL, "PO_BOX" VARCHAR2(5) NOT NULL, 
    "HOME_PHONE" VARCHAR2(9) NOT NULL, "JOB_PHONE" VARCHAR2(9) NOT 
    NULL, "MOB_PHONE" VARCHAR2(9) NOT NULL, "EMAIL" VARCHAR2(255) 
    NOT NULL, "CITY" VARCHAR2(30) NOT NULL, "COUNTRY_ID" VARCHAR2(3) 
    NOT NULL, 
    CONSTRAINT "PK_CUSTOMER" PRIMARY KEY("CUSTOMER_ID"), 
    CONSTRAINT "UQ_CUSTOMER" UNIQUE("CUSTOMER_ID"), 
    CONSTRAINT "FK_COUNTRY" FOREIGN KEY("COUNTRY_ID") 
    REFERENCES "TRADIA"."COUNTRIES"("COUNTRY_ID")) 
    TABLESPACE "TRADIA"