CREATE TABLE "TRADIA"."BROKER_DEALS"("BROKER_DEAL_ID" VARCHAR2(
    10) NOT NULL, "BROKER_ID" VARCHAR2(4) NOT NULL, "AMOUNT" NUMBER(
    15, 2) NOT NULL, "SIDE" VARCHAR2(1) NOT NULL, "CLEARED" VARCHAR2(
    1) NOT NULL, 
    CONSTRAINT "PK_BRK_DEAL" PRIMARY KEY("BROKER_DEAL_ID"), 
    CONSTRAINT "UQ_BRK_DEAL" UNIQUE("BROKER_DEAL_ID"), 
    CONSTRAINT "FK_BD_BROKER" FOREIGN KEY("BROKER_ID") 
    REFERENCES "TRADIA"."BROKERS"("BROKER_ID"), 
    CONSTRAINT "CHK_CLEARED" CHECK(cleared in('Y','y','N','n')), 
    CONSTRAINT "CHK_SIDE" CHECK(side in('B','b','S','s'))) 
    TABLESPACE "TRADIA"