CREATE TABLE "TRADIA"."TIME_IN_FORCES"("TIME_IN_FORCE_ID" 
    VARCHAR2(2) NOT NULL, "TIME_DESCRIPTION" VARCHAR2(20) NOT NULL, 
    CONSTRAINT "PK_FORCE" PRIMARY KEY("TIME_IN_FORCE_ID"), 
    CONSTRAINT "UQ_FORCE" UNIQUE("TIME_IN_FORCE_ID")) 
    TABLESPACE "TRADIA" 