CREATE TABLE "TRADIA"."STOCK_ORDER_STATUS"("ORDER_STATUS_ID" 
    VARCHAR2(2) NOT NULL, "STATUS_DESCRIPTION" VARCHAR2(20) NOT NULL, 
    CONSTRAINT "PK_OSTAT" PRIMARY KEY("ORDER_STATUS_ID"), 
    CONSTRAINT "UQ_OSTAT" UNIQUE("ORDER_STATUS_ID")) 
    TABLESPACE "TRADIA"