CREATE TABLE "TRADIA"."STOCK_ORDERS"("ORDER_ID" VARCHAR2(20) NOT NULL, 
    "MESSAGE_TYPE_ID" VARCHAR2(2) NOT NULL, "CANCEL_ORDER_ID" 
    VARCHAR2(20) NOT NULL, "AMEND_ORDER_ID" VARCHAR2(20) NOT NULL, 
    "BROKER_ID" VARCHAR2(4) NOT NULL, "ISIN_CODE_ID" VARCHAR2(20) 
    NOT NULL, "BUY_SELL_INDEX" VARCHAR2(1) NOT NULL, "MARKET_ID" 
    VARCHAR2(2) NOT NULL, "ACCOUNT_ID" VARCHAR2(20) NOT NULL, 
    "DATE_LIMIT" DATE NOT NULL, "PRICE_LIMIT" NUMBER(16, 3) NOT NULL, 
    "ORDER_TYPE_ID" VARCHAR2(1) NOT NULL, "CURRENCY_LIQ_ID" VARCHAR2(
    3) NOT NULL, "TIME_IN_FORCE_ID" VARCHAR2(2) NOT NULL, "TEXT" 
    VARCHAR2(255) NOT NULL, 
    CONSTRAINT "PK_STOCKS" PRIMARY KEY("ORDER_ID", 
    "MESSAGE_TYPE_ID"), 
    CONSTRAINT "UQ_ORDER" UNIQUE("ORDER_ID"), 
    CONSTRAINT "UQ_CANCEL" UNIQUE("CANCEL_ORDER_ID"), 
    CONSTRAINT "UQ_AMEND" UNIQUE("AMEND_ORDER_ID"), 
    CONSTRAINT "FK_MSGTYPE" FOREIGN KEY("MESSAGE_TYPE_ID") 
    REFERENCES "TRADIA"."MESSAGE_TYPES"("MESSAGE_TYPE_ID"), 
    CONSTRAINT "FK_BROKER" FOREIGN KEY("BROKER_ID") 
    REFERENCES "TRADIA"."BROKERS"("BROKER_ID"), 
    CONSTRAINT "FK_ISIN" FOREIGN KEY("ISIN_CODE_ID") 
    REFERENCES "TRADIA"."ISIN_CODES"("ISIN_CODE_ID"), 
    CONSTRAINT "FK_MARKET" FOREIGN KEY("MARKET_ID") 
    REFERENCES "TRADIA"."MARKETS"("MARKET_ID"), 
    CONSTRAINT "FK_ORDERTYPE" FOREIGN KEY("ORDER_TYPE_ID") 
    REFERENCES "TRADIA"."ORDER_TYPES"("ORDER_TYPE_ID"), 
    CONSTRAINT "FK_S_CURRENCY" FOREIGN KEY("CURRENCY_LIQ_ID") 
    REFERENCES "TRADIA"."CURRENCIES"("CURRENCY_ID"), 
    CONSTRAINT "FK_TIME" FOREIGN KEY("TIME_IN_FORCE_ID") 
    REFERENCES "TRADIA"."TIME_IN_FORCES"("TIME_IN_FORCE_ID")) 
    TABLESPACE "TRADIA"