CREATE TABLE "TRADIA"."COUNTRIES"("COUNTRY_ID" VARCHAR2(3) NOT 
    NULL, "COUNTRY_NAME" VARCHAR2(20) NOT NULL, 
    CONSTRAINT "PK_COUNTRY" PRIMARY KEY("COUNTRY_ID"), 
    CONSTRAINT "UQ_COUNTRY" UNIQUE("COUNTRY_ID")) 
    TABLESPACE "TRADIA"