CREATE TABLE "TRADIA"."CURRENCIES"("CURRENCY_ID" VARCHAR2(3) NOT 
    NULL, "CURRENCY_NAME" VARCHAR2(20) NOT NULL, 
    CONSTRAINT "PK_CURRENCY" PRIMARY KEY("CURRENCY_ID"), 
    CONSTRAINT "UQ_CURRENCY" UNIQUE("CURRENCY_ID")) 
    TABLESPACE "TRADIA" 