CREATE TABLE "TRADIA"."BROKERS"("BROKER_ID" VARCHAR2(4) NOT NULL, 
    "BROKER_NAME" VARCHAR2(30) NOT NULL, 
    CONSTRAINT "PK_BROKER" PRIMARY KEY("BROKER_ID"), 
    CONSTRAINT "UQ_BROKER" UNIQUE("BROKER_ID")) 
    TABLESPACE "TRADIA" 