CREATE TABLE "TRADIA"."TRANSFER_DEALS"("TRANSFER_ID" VARCHAR2(
    20) NOT NULL, "SOURCE_ACCOUNT" VARCHAR2(20) NOT NULL, 
    "DEST_ACCOUNT" VARCHAR2(20) NOT NULL, "DATE_DEAL" DATE NOT NULL, 
    "AMOUNT" NUMBER(15, 2) NOT NULL, "CURRENCY_ID" VARCHAR2(3) NOT 
    NULL, "COMMENTS" VARCHAR2(30) NOT NULL, "COMMISION_FEE" NUMBER(8, 
    2) NOT NULL, 
    CONSTRAINT "PK_TRANSFER" PRIMARY KEY("TRANSFER_ID"), 
    CONSTRAINT "UQ_TRANSFER" UNIQUE("TRANSFER_ID"), 
    CONSTRAINT "FK_CURRENCY" FOREIGN KEY("CURRENCY_ID") 
    REFERENCES "TRADIA"."CURRENCIES"("CURRENCY_ID")) 
    TABLESPACE "TRADIA"