CREATE TABLE "TRADIA"."CUSTOMERS_ACCOUNTS"("CUSTOMER_ID" VARCHAR2(10) 
    NOT NULL, "ACCOUNT_ID" VARCHAR2(20) NOT NULL, 
    CONSTRAINT "PK_CUSTS_ACCS" PRIMARY KEY("CUSTOMER_ID", 
    "ACCOUNT_ID"), 
    CONSTRAINT "FK_CUSTOMER" FOREIGN KEY("CUSTOMER_ID") 
    REFERENCES "TRADIA"."CUSTOMERS"("CUSTOMER_ID"), 
    CONSTRAINT "FK_ACCOUNT" FOREIGN KEY("ACCOUNT_ID") 
    REFERENCES "TRADIA"."CUSTOMER_ACCOUNT"("ACCOUNT_ID")) 
    TABLESPACE "TRADIA"