CREATE TABLE "TRADIA"."ORDER_TYPES"("ORDER_TYPE_ID" VARCHAR2(1) 
    NOT NULL, "TYPE_DESCRIPTION" VARCHAR2(15) NOT NULL, 
    CONSTRAINT "PK_OTYPE" PRIMARY KEY("ORDER_TYPE_ID"), 
    CONSTRAINT "UQ_OTYPE" UNIQUE("ORDER_TYPE_ID")) 
    TABLESPACE "TRADIA" 