CREATE TABLE "TRADIA"."DEAL_SETTLEMENTS"("PAYMENT_ORDER_ID" 
    VARCHAR2(10) NOT NULL, "BROKER_DEAL_ID" VARCHAR2(10) NOT NULL, 
    "DATE_PAID" DATE NOT NULL, "CURRENCY_ID" VARCHAR2(3) NOT NULL, 
    "ORDERING_INSTITUTION" VARCHAR2(11) NOT NULL, 
    "BENEFICIARY_INSTITUTION" VARCHAR2(11) NOT NULL, "CORRESP_ID" 
    VARCHAR2(2) NOT NULL, "DOCUMENT" BLOB NOT NULL, 
    CONSTRAINT "PK_DEAL_SETT" PRIMARY KEY("PAYMENT_ORDER_ID"), 
    CONSTRAINT "UQ_DEAL_SETT" UNIQUE("PAYMENT_ORDER_ID"), 
    CONSTRAINT "FK_DS_BRKDEAL" FOREIGN KEY("BROKER_DEAL_ID") 
    REFERENCES "TRADIA"."BROKER_DEALS"("BROKER_DEAL_ID"), 
    CONSTRAINT "FK_DS_CURRENCY" FOREIGN KEY("CURRENCY_ID") 
    REFERENCES "TRADIA"."CURRENCIES"("CURRENCY_ID"), 
    CONSTRAINT "FK_DS_CORRESP" FOREIGN KEY("CORRESP_ID") 
    REFERENCES "TRADIA"."CORRESPONDENTS"("CORRESP_ID")) 
    TABLESPACE "TRADIA"