CREATE TABLE "TRADIA"."MARKETS"("MARKET_ID" VARCHAR2(2) NOT NULL, 
    "MARKET_NAME" VARCHAR2(30) NOT NULL, 
    CONSTRAINT "PK_MARKET" PRIMARY KEY("MARKET_ID"), 
    CONSTRAINT "UQ_MARKET" UNIQUE("MARKET_ID")) 
    TABLESPACE "TRADIA" 