INSERT INTO countries (country_id, country_name) VALUES ('ESP', 'SPAIN')
INSERT INTO countries (country_id, country_name) VALUES ('US', 'United States of America')
INSERT INTO countries (country_id, country_name) VALUES ('GER', 'Germany')
INSERT INTO countries (country_id, country_name) VALUES ('AUT', 'Austria')
INSERT INTO countries (country_id, country_name) VALUES ('UK', 'United Kingdom')
INSERT INTO countries (country_id, country_name) VALUES ('FRA', 'France')
INSERT INTO countries (country_id, country_name) VALUES ('ITA', 'Italy')
INSERT INTO countries (country_id, country_name) VALUES ('AUS', 'Australia')
INSERT INTO countries (country_id, country_name) VALUES ('NZD', 'New Zealand')