INSERT INTO MARKETS VALUES('CI','Abidjan Stock Exchange');
INSERT INTO MARKETS VALUES('A','American Stock Exchange');
INSERT INTO MARKETS VALUES('AM','Amman Stock Exchange');
INSERT INTO MARKETS VALUES('E','AEX Options and Futures Exchange');
INSERT INTO MARKETS VALUES('AS','AEX Stock Exchange');
INSERT INTO MARKETS VALUES('AX','Australian Stock Exchange');
INSERT INTO MARKETS VALUES('BH','Bahrain Stock Exchange');
INSERT INTO MARKETS VALUES('BA','Barcelona Stock Exchange - Floor Trading');
INSERT INTO MARKETS VALUES('BC','Barcelona Stock Exchange');
INSERT INTO MARKETS VALUES('BY','Beirut Stock Exchange');
INSERT INTO MARKETS VALUES('b','Belfox');
INSERT INTO MARKETS VALUES('BE','Berlin Stock Exchange');
INSERT INTO MARKETS VALUES('BN','Berne Stock Exchange');
INSERT INTO MARKETS VALUES('BI','Bilbao Stock Exchange');
INSERT INTO MARKETS VALUES('BO','Bombay Stock Exchange');
INSERT INTO MARKETS VALUES('B','Boston Stock Exchange');
INSERT INTO MARKETS VALUES('BT','Botswana Share Market');
INSERT INTO MARKETS VALUES('BM','Bremen Stock Exchange');
INSERT INTO MARKETS VALUES('BR','Brussels Stock Exchange');
INSERT INTO MARKETS VALUES('CL','Calcutta Stock Exchange');
INSERT INTO MARKETS VALUES('V','Canadian Ventures Exchange');
INSERT INTO MARKETS VALUES('CH','Channel Islands');
INSERT INTO MARKETS VALUES('W','Chicago Board Options Exchange');
INSERT INTO MARKETS VALUES('MW','Chicago Stock Exchange');
INSERT INTO MARKETS VALUES('CE','Chile Electronic Exchange');
INSERT INTO MARKETS VALUES('C','Cincinnati Stock Exchange');
INSERT INTO MARKETS VALUES('CM','Colombo Stock Exchange');
INSERT INTO MARKETS VALUES('CO','Copenhagen Stock Exchange');
INSERT INTO MARKETS VALUES('DL','Dehli Stock Exchange');
INSERT INTO MARKETS VALUES('QA','Doha Securities Market');
INSERT INTO MARKETS VALUES('DU','Dubai Financial Market');
INSERT INTO MARKETS VALUES('D','Dusseldorf Stock Exchange');
INSERT INTO MARKETS VALUES('EB','Electronic Stock Exchange of Venezuela');
INSERT INTO MARKETS VALUES('F','Frankfurt Stock Exchange');
INSERT INTO MARKETS VALUES('FU','Fukuoka Stock Exchange');
INSERT INTO MARKETS VALUES('GH','Ghana Stock Exchange');
INSERT INTO MARKETS VALUES('H','Hamburg Stock Exchange');
INSERT INTO MARKETS VALUES('HA','Hanover Stock Exchange');
INSERT INTO MARKETS VALUES('HE','Helsinki Stock Exchange');
INSERT INTO MARKETS VALUES('HK','Hong Kong Stock Exchange');
INSERT INTO MARKETS VALUES('IC','Iceland Stock Exchange');
INSERT INTO MARKETS VALUES('IN','Interbolsa (Portugal)');
INSERT INTO MARKETS VALUES('Y','International Securities Exchange (ISE)');
INSERT INTO MARKETS VALUES('I','Irish Stock Exchange');
INSERT INTO MARKETS VALUES('IS','Istanbul Stock Exchange');
INSERT INTO MARKETS VALUES('JK','Jakarta Stock Exchange');
INSERT INTO MARKETS VALUES('Q','Japanese Securities Dealers Association (JASDAQ)');
INSERT INTO MARKETS VALUES('J','Johannesburg Stock Exchange');
INSERT INTO MARKETS VALUES('KA','Karachi Stock Exchange');
INSERT INTO MARKETS VALUES('KQ','KOSDAQ (Korea)');
INSERT INTO MARKETS VALUES('KZ','Kazakhstan Stock Exchange');
INSERT INTO MARKETS VALUES('KS','Korea Stock Exchange');
INSERT INTO MARKETS VALUES('KL','Kuala Lumpur Stock Exchange');
INSERT INTO MARKETS VALUES('KW','Kuwait Stock Exchange');
INSERT INTO MARKETS VALUES('KY','Kyoto Stock Exchange');
INSERT INTO MARKETS VALUES('LG','Lagos Stock Exchange');
INSERT INTO MARKETS VALUES('LA','Latin American Market in Spain (LATIBEX)');
INSERT INTO MARKETS VALUES('LN','Le Nouveau Marche');
INSERT INTO MARKETS VALUES('LM','Lima Stock Exchange');
INSERT INTO MARKETS VALUES('LS','Lisbon Stock Exchange');
INSERT INTO MARKETS VALUES('L','London Stock Exchange');
INSERT INTO MARKETS VALUES('LZ','Lusaka Stock Exchange');
INSERT INTO MARKETS VALUES('LU','Luxembourg Stock Exchange');
INSERT INTO MARKETS VALUES('MD','Madras Stock Exchange');
INSERT INTO MARKETS VALUES('MA','Madrid Stock Exchange - Floor Trading');
INSERT INTO MARKETS VALUES('MC','Madrid Stock Exchange');
INSERT INTO MARKETS VALUES('MT','Malta Stock Exchange');
INSERT INTO MARKETS VALUES('MZ','Mauritius Stock Exchange');
INSERT INTO MARKETS VALUES('ML','Medellin Stock Excahnge');
INSERT INTO MARKETS VALUES('MX','Mexican Stock Exchange');
INSERT INTO MARKETS VALUES('MI','Milan Stock Exchange');
INSERT INTO MARKETS VALUES('p','MONEP Paris Stock Options');
INSERT INTO MARKETS VALUES('M','Montreal Exchange');
INSERT INTO MARKETS VALUES('MM','Moscow Inter Bank Currency Exchange');
INSERT INTO MARKETS VALUES('MO','Moscow Stock Exchange');
INSERT INTO MARKETS VALUES('MU','Munich Stock Exchange');
INSERT INTO MARKETS VALUES('OM','Muscat Stock Exchange');
INSERT INTO MARKETS VALUES('NM','Namibia Stock Exchange');
INSERT INTO MARKETS VALUES('NG','Nagoya Stock Exchange');
INSERT INTO MARKETS VALUES('NR','Nairobi Stock Exchange');
INSERT INTO MARKETS VALUES('O','NASDAQ');
INSERT INTO MARKETS VALUES('OB','NASDAQ Dealers - Bulletin Board');
INSERT INTO MARKETS VALUES('OJ','NASDAQ Japan');
INSERT INTO MARKETS VALUES('NS','National Stock Exchange of India');
INSERT INTO MARKETS VALUES('N','New York Stock Exchange');
INSERT INTO MARKETS VALUES('NZ','New Zealand Stock Exchange');
INSERT INTO MARKETS VALUES('NW','NewEx (Austria)');
INSERT INTO MARKETS VALUES('OD','Occidente Stock Exchange');
INSERT INTO MARKETS VALUES('OS','Osaka Stock Exchange');
INSERT INTO MARKETS VALUES('OL','Oslo Stock Exchange');
INSERT INTO MARKETS VALUES('P','Pacific Stock Exchange');
INSERT INTO MARKETS VALUES('PA','Paris Stock Exchange');
INSERT INTO MARKETS VALUES('PH','Philadelphia Stock Exchange');
INSERT INTO MARKETS VALUES('X','Philadelphia Stock Exchange Options');
INSERT INTO MARKETS VALUES('PS','Phillipine Stock Exchange');
INSERT INTO MARKETS VALUES('PNK','Pink Sheets (National Quotation Bureau)');
INSERT INTO MARKETS VALUES('PR','Prague Stock Exchange');
INSERT INTO MARKETS VALUES('RQ','RASDAQ (Romania)');
INSERT INTO MARKETS VALUES('RI','Riga Stock Exchange');
INSERT INTO MARKETS VALUES('SO','Rio de Janeiro OTC Stock Exchange (SOMA)');
INSERT INTO MARKETS VALUES('RTS','Russian Trading System');
INSERT INTO MARKETS VALUES('SN','Santiago Stock Exchange');
INSERT INTO MARKETS VALUES('SA','Sao Paulo Stock Exchange');
INSERT INTO MARKETS VALUES('SP','Sapporo Stock Exchange');
INSERT INTO MARKETS VALUES('SE','Saudi Stock Exchange');
INSERT INTO MARKETS VALUES('SBI','SBI Stock Exchange (Sweden)');
INSERT INTO MARKETS VALUES('SI','Singapore Stock Exchange');
INSERT INTO MARKETS VALUES('SS','Shanghai Stock Exchange');
INSERT INTO MARKETS VALUES('SZ','Shenzhen Stock Exchange');
INSERT INTO MARKETS VALUES('ST','Stockholm Stock Exchange');
INSERT INTO MARKETS VALUES('SG','Stuttgart Stock Exchange');
INSERT INTO MARKETS VALUES('PE','St. Petersburg Stock Exchange');
INSERT INTO MARKETS VALUES('S','SWX Swiss Exchange');
INSERT INTO MARKETS VALUES('SU','Surabaya Stock Exchange');
INSERT INTO MARKETS VALUES('TWO','Taiwan OTC Securities Exchange');
INSERT INTO MARKETS VALUES('TW','Taiwan Stock Exchange');
INSERT INTO MARKETS VALUES('TL','Tallinn Stock Exchange');
INSERT INTO MARKETS VALUES('TA','Tel Aviv Stock Exchange');
INSERT INTO MARKETS VALUES('BK','Thailand Stock Exchange');
INSERT INTO MARKETS VALUES('TH','Third Market');
INSERT INTO MARKETS VALUES('T','Tokyo Stock Exchange');
INSERT INTO MARKETS VALUES('K','Toronto Options Exchange');
INSERT INTO MARKETS VALUES('TO','Toronto Stock Exchange');
INSERT INTO MARKETS VALUES('TP','Tradepoint Stock Exchange');
INSERT INTO MARKETS VALUES('TN','Tunis Stock Exchange');
INSERT INTO MARKETS VALUES('PFT','Ukraine PFTS');
INSERT INTO MARKETS VALUES('VA','Valencia Stock Exchange');
INSERT INTO MARKETS VALUES('VL','Vilnus Stock Exchange');
INSERT INTO MARKETS VALUES('VI','Vienna Stock Exchange');
INSERT INTO MARKETS VALUES('VX','virt-x');
INSERT INTO MARKETS VALUES('DE','Xetra');
INSERT INTO MARKETS VALUES('ZA','Zagreb Stock Exchange');
INSERT INTO MARKETS VALUES('ZI','Zimbabwe Stock Exchange');